---
kind: pipeline
name: default

steps:
  - name: weblinks-codeception-tests
    image: joomlaprojects/docker-systemtests:latest
    commands:
      - composer install
      - chmod a+x .drone/build.sh
      - ./.drone/build.sh
      - apache2ctl start
      - service mysql start
      - cd /tests/www
      - export DISPLAY=:0
      - Xvfb -screen 0 1024x768x24 -ac +extension GLX +render -noreset > /dev/null 2>&1 &
      - sleep 3
      - fluxbox  > /dev/null 2>&1 &
      - vendor/bin/robo run:tests

  - name: artifacts-system-tests
    image: cschlosser/drone-ftps
    depends_on: [ weblinks-codeception-tests ]
    environment:
      FTP_USERNAME:
        from_secret: ftpusername
      FTP_PASSWORD:
        from_secret: ftppassword
      PLUGIN_HOSTNAME: ci.joomla.org:21
      PLUGIN_SRC_DIR: /tests/_output/
      PLUGIN_DEST_DIR: /artifacts
      PLUGIN_SECURE: false
      PLUGIN_EXCLUDE: ^\.git/$
    commands:
      - export PLUGIN_DEST_DIR=$PLUGIN_DEST_DIR/$DRONE_REPO/$DRONE_BRANCH/$DRONE_PULL_REQUEST_$DRONE_BUILD_NUMBER/system-tests
      - echo https://ci.joomla.org:444$PLUGIN_DEST_DIR
      - /bin/upload.sh
    when:
      status:
      - failure

volumes:
  - name: weblinks_cache
    host:
      path: /tmp/weblinks_cache

---
kind: signature
hmac: 9346f0e74d2605ebe7bc9d33ad0588c1073ba3a9d9b254b71a7a85e219089449

...
